### ISSUE TITLE
Integrate new 2.13 collection types

### ISSUE THREAD

**Issue by lrytz** [scala/scala-java8-compat#113]
Provide (optimized) stream converters (if necessary?) for new collections in 2.13
  - ChampHashSet / ChampHashMap (they will probably be renamed to HashMap / HashSet)
  - mutable / immutable ArraySeq
  - ArrayDeque

**Comment by SethTisue** [comment]
@lrytz should this be closed?

**Comment by lrytz** [comment]
Yep, at least here :-)
