### ISSUE TITLE
FutureConverters `toJava` and `toScala` should be `asJava` and `asScala` if they only wrap

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-java8-compat#116]
we normally use `as` for wrappers and `to` for things that convert by copying

(FutureConverters and perhaps elsewhere, audit needed)

**Comment by SethTisue** [comment]
volunteer to add the new names and deprecate the old names?

**Comment by lrytz** [comment]
Argh, missed this while migrating the converters to 2.13 std lib. I'll fix it in RC3 if there's one.

**Comment by SethTisue** [comment]
@lrytz did this end up being addressed?

**Comment by lrytz** [comment]
From @NthPortal with ❤️ https://github.com/scala/scala/pull/8094
