### ISSUE TITLE
Publish for 2.13.0-RC2

### ISSUE THREAD

**Issue by raboof** [scala/scala-java8-compat#145]
See also #139

**Comment by lrytz** [comment]
I'll take a look today. I'd like to fix https://github.com/scala/scala-java8-compat/issues/144 for the RC2 release though. Not sure if I need to change the version number, or using 0.9.0 again would be ok :)

**Comment by raboof** [comment]
:+1: - pushed my wip as #146 - haven't checked it really makes sense though, I just "followed the types"

**Comment by lrytz** [comment]
We'll need genjavadoc as well

**Comment by raboof** [comment]
https://github.com/lightbend/genjavadoc/pull/173

**Comment by lrytz** [comment]
The release is on staging https://oss.sonatype.org/content/repositories/staging/org/scala-lang/modules/scala-java8-compat_2.13.0-RC2, I released the staging repo, and it's no longer in the list on nexus. but didn't show up on central yet (http://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.13.0-RC2).

**Comment by lrytz** [comment]
ah, the missing trailing slash was the problem.. http://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.13.0-RC2/
