### ISSUE TITLE
Release version 1.0?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-java8-compat#213]
We've been in 0.9 releases for a long, long time now. We're adding MiMa in #211. I think it would be reasonable at this point to say, hey, this is 1.0 now. (We could do an RC first.)

**Comment by SethTisue** [comment]
I guess I'll do this when Scala 3.0.0-RC2 comes out, since I'll need to be doing publishing then anyway.

**Comment by SethTisue** [comment]
Scala 3.0.0-RC2 is out. I will roll scala-java8-compat 1.0.0-RC1 today.

**Comment by SethTisue** [comment]
1.0.0-RC1 is published

**Comment by smarter** [comment]
By the way, shouldn't this library be deprecated since most (all?) of its converters were merged into the 2.13 standard library (https://github.com/scala/scala/pull/7458) ?

**Comment by SethTisue** [comment]
uh, good question. I don't think absolutely everything was moved, and stuff being in 2.13 doesn't help people crossbuilding to 2.11 and 2.12.

at minimum, the README should be clear about what the situation is, for sure

perhaps we could have a 1.x series that keeps everything, and 2.x series that is 2.13+ only — if there are any converters that weren't ported, that is. if everything was ported, then the readme could just say "you don't need this if you're on 2.13+ only"

from the checklist on Lukas's PR it seems he intended to "make java8-compat a shim release for 2.13 that helps cross-building a codebase with 2.12 / 2.13", which would be a little different, I guess that means support cross-building by forwarding to the 2.13 stdlib implementations. that sounds nice, but it also sounds like work I don't want to do

**Comment by lrytz** [comment]
> I don't think absolutely everything was moved

I think we moved everything, the only reason to keep this for 2.13 was cross-building with older Scala versions.

IIRC, we kept the converters in the 2.13 version of this module because it was the easiest way forward. The actual colleciton types are aliased: https://github.com/scala/scala-java8-compat/blob/main/src/main/scala-2.13+/scala/compat/java8/collectionImpl/package.scala

So "you don't need this if you're on 2.13+ only" is right.

**Comment by SethTisue** [comment]
thanks — I'll update the readme appropriately at the time I do the 1.0 release

**Comment by SethTisue** [comment]
I have backpublished 1.0.0-RC1 for Scala 3.0.0-RC3. (Without doing anything else, yet.)

**Comment by SethTisue** [comment]
only publishing remains: #228
