### ISSUE TITLE
Maven Version 0.5.0 seems not complete

### ISSUE THREAD

**Issue by wir33658** [scala/scala-java8-compat#51]
Check out http://search.maven.org/#artifactdetails%7Corg.scala-lang.modules%7Cscala-java8-compat_2.11%7C0.5.0%7Cbundle

and you will see there is no "scala.compat.java8.FunctionConverters"

(Checking the "build.sbt" it looks like this should have been generated, I guess its not and something went wrong)

**Comment by retronym** [comment]
This will be part of [0.6.0](https://github.com/scala/scala-java8-compat/issues?utf8=%E2%9C%93&q=milestone%3A0.6.0+). I had the milestone incorrectly to an already-released 0.5.0 version of a few issues. I've just corrected that.
