### ISSUE TITLE
Make Scala 2.10 release with serialization fix?

### ISSUE THREAD

**Issue by vsipuli** [scala/scala-java8-compat#59]
Scala 2.10 was dropped in an earlier pull request before functional interfaces were made serializable in commit `4bb7192f394297c09edba08da56fdc181fd33c10`. Would it please be possible to make a last release (0.5.1 branch?) with Scala 2.10 support that includes the aforementioned serialization fix? (The last published artifacts with Scala 2.10 support: http://mvnrepository.com/artifact/org.scala-lang.modules/scala-java8-compat_2.10)

The reason for asking this is that [Apache Spark](http://spark.apache.org/) requires Scala 2.10, but the function interfaces generated in 0.5.0 are not serializable and hence cannot be used in tasks on a Spark cluster. Would be great if scala-java8-compat was usable with Spark.

**Comment by SethTisue** [comment]
Spark is on 2.11 these days
