### ISSUE TITLE
publish for 2.12.0-M3 (and future versions of Scala)

### ISSUE THREAD

**Issue by rkuhn** [scala/scala-java8-compat#64]
Akka now depends on this library to provide bridges for Future and Option, so we cannot release for Scala 2.12 milestones without this library being released first.

**Comment by retronym** [comment]
https://oss.sonatype.org/service/local/repositories/releases/content/org/scala-lang/modules/scala-java8-compat_2.12.0-M3/0.7.0

Future releases will be cross built. We don't have a automated tool to publish when a new Scala milestone is added, but I'll try to remember to do so.

**Comment by rkuhn** [comment]
Thanks a lot, Jason!

**Comment by lrytz** [comment]
I once came up with a script that simplifies publishing releases from a local machine: https://github.com/scala/scala-partest/pull/37, but we're not sure what's the best place to put it.

**Comment by SethTisue** [comment]
I added it to https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md
