### ISSUE TITLE
publish against 2.12.0-M5

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-java8-compat#72]
Still publishing against M4, according to https://github.com/scala/scala-java8-compat/blob/master/build.sbt#L13

**Comment by szeiger** [comment]
I was sure https://github.com/scala/scala-java8-compat/pull/71 had been merged. Let's try again with a new RC...

**Comment by szeiger** [comment]
https://github.com/scala/scala-java8-compat/releases/tag/v0.8.0-RC3 published
