### ISSUE TITLE
release 1.0.0 on 2.12.0

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-java8-compat#77]
- [X] fix 2.12 compat: https://github.com/scala/scala-java8-compat/pull/76
- [ ] bring back convenience that was lost with https://github.com/scala/scala/pull/5298 (we'll keep the classes in scala/scala as-is)

**Comment by adriaanm** [comment]
@szeiger, could you take the lead on getting scala-java8-compat 1.0.0 out along with 2.12?

@retronym, please add your suggestions on how to proceed to my todo list above (my meeting notes were a bit sketch)

**Comment by szeiger** [comment]
Moving JFunction and related classes back into scala-java8-compat: https://github.com/scala/scala-java8-compat/pull/78

**Comment by schmitch** [comment]
It's also important to look into: #74 after #78. would be not cool to have 1.0.0 without `JFunction` at all.
