### ISSUE TITLE
ScalaStreamSupport class seems to be missing

### ISSUE THREAD

**Issue by gabro** [scala/scala-java8-compat#80]
Hi,
I included the library (version 0.7.0) in my Java project and when I try importing `ScalaStreamSupport`:

```java
import scala.compat.java8.ScalaStreamSupport;
```

```scala
[error] <...>.java:6: cannot find symbol
[error]   symbol:   class ScalaStreamSupport
[error]   location: package scala.compat.java8
[error] scala.compat.java8.ScalaStreamSupport
```

Am I missing something?

**Comment by gabro** [comment]
If it can help, I'm able to use other features of the library, like `FutureConverters`

**Comment by SethTisue** [comment]
try 0.8.0-RC7

**Comment by gabro** [comment]
Thanks @SethTisue, that seems to be working
