### ISSUE TITLE
Weird error when working with StreamConverters

### ISSUE THREAD

**Issue by nartamonov** [scala/scala-java8-compat#87]
Hi all! Following semantically correct code throws weird runtime error:

```scala
import scala.compat.java8.StreamConverters._
import java.util.stream.Collectors

val sampleItems = Iterator.fill(120)("a").toVector
val subset = sampleItems.slice(0, 40)
val subsetAsStream = subset.seqStream

// Throws
// java.lang.NullPointerException:
// at scala.compat.java8.converterImpl.StepsAnyVector.next(StepsVector.scala:66)
// at scala.compat.java8.collectionImpl.AnyStepper.forEachRemaining(Stepper.scala:230)
// at scala.compat.java8.collectionImpl.AnyStepper.forEachRemaining$(Stepper.scala:230)
// at scala.compat.java8.converterImpl.StepsLikeIndexed.forEachRemaining(StepsLikeIndexed.scala:28)
// at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
// at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
// at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
// at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
// at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
val subsetAsJList = subsetAsStream.collect(Collectors.toList())
```

**Comment by SethTisue** [comment]
still reproducible. more compactly, it's `Vector.fill(120)("a").slice(0, 40).seqStream.collect(Collectors.toList())`

**Comment by SethTisue** [comment]
looks like a subtle bug in `StepsVector`

**Comment by SethTisue** [comment]
Rex says scold him if he doesn't get to it this week.

**Comment by SethTisue** [comment]
ping @Ichoran

**Comment by SethTisue** [comment]
Rex, you are SCOLDED

**Comment by Ichoran** [comment]
@SethTisue - Thanks!  Unfortunately I'm at a conference all week and will forget it ever happened before I get back home.  You will probably have to scold me again next week!

**Comment by SethTisue** [comment]
I'm good at scolding.

**Comment by SethTisue** [comment]
@Ichoran scold scold scold

**Comment by Ichoran** [comment]
Didn't quite get finished.  I'll wrap it up tonight if I get any more time.

**Comment by Ichoran** [comment]
I won't get time to finish until Wednesday night.

**Comment by Ichoran** [comment]
Argh, place I intended to work closed an hour early.  I think I'm very close.

**Comment by Ichoran** [comment]
@SethTisue - https://github.com/scala/scala-java8-compat/pull/117 (I forgot the magic words that would link it automatically to the issue.)
